name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    name: R CMD check (OS: ${{ matrix.config.os }}, R: ${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: 'release' }
          - { os: ubuntu-latest,  r: 'release' }

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
